balloscope_core:
    resource: "@BalloscopeCoreBundle/Controller/"
    type:     annotation
    prefix:   /

# FOS js Routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
