<?php

namespace Balloscope\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BallRepository extends EntityRepository
{
}
